stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375/
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

deploy:
  stage: deploy
  image: alpine:latest
  script:
    - apk add --no-cache openssh
    - echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
    - ssh -o StrictHostKeyChecking=no -i private_key $DEPLOY_USER@$DEPLOY_HOST "docker pull $IMAGE_TAG && docker stop otp-service || true && docker rm otp-service || true && docker run -d --name otp-service -p 3000:3000 $IMAGE_TAG"
  only:
    - main
